matrix:
    include:
        - language: nix
          nix: 2.2.2
          if: type = pull_request
          script: 
            # This is because the unstable channel has not been updated yet
            - nix-env -f https://github.com/NixOS/nixpkgs/archive/1f5fa9a8298ec7411431da981b4f1a79e10f2a8e.tar.gz -i hydra-cli
            - hydra-cli -H https://hydra.nix.corp.cloudwatt.com jobset-wait hydra-cli $TRAVIS_PULL_REQUEST
        - language: rust
          rust: 
            - stable
          cache: cargo
